on:
  workflow_dispatch:
    inputs:
      USE_MTWIFI_CFG:
        description: 'Use mtwifi-cfg'
        required: true
        default: true
        type: boolean
      USE_NX30PRO_EEPROM:
        description: 'Use nx30pro eeprom'
        required: true
        default: true
        type: boolean
      USE_52MHZ:
        description: 'Use 52MHz max-frequency'
        required: true
        default: true
        type: boolean
      USE_MHZ:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - 52MHZ
          - 52MHZ
          - 13MHZ
